from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import date
from decimal import Decimal
from pathlib import Path
from typing import Iterable

from .research import Candidate

CANDIDATES_FILE = "PREMARKET-CANDIDATES.json"
TRADE_DECISIONS = {"candidate", "trade_candidate", "approved", "buy", "paper_trade_candidate"}


@dataclass(frozen=True)
class PremarketSignal:
    symbol: str
    catalyst: str
    mcp_score: Decimal = Decimal("0")
    sources: tuple[str, ...] = ()
    exchange: str | None = None
    decision: str = "candidate"
    notes: str = ""


def normalize_symbol(value: object) -> str:
    """Normalize MCP symbols such as NASDAQ:NVDA to Alpaca/Yahoo-style NVDA."""
    symbol = str(value or "").upper().strip()
    if ":" in symbol:
        symbol = symbol.rsplit(":", 1)[-1]
    return symbol.replace("/", "-").strip()


def candidates_path(root: Path) -> Path:
    return root / "memory" / CANDIDATES_FILE


def _as_decimal(value: object) -> Decimal:
    try:
        return Decimal(str(value))
    except Exception:
        return Decimal("0")


def load_premarket_signals(root: Path, *, today: date | None = None) -> tuple[list[PremarketSignal], str]:
    today = today or date.today()
    path = candidates_path(root)
    if not path.exists():
        return [], f"missing {path.relative_to(root)}"
    try:
        payload = json.loads(path.read_text())
    except Exception as exc:
        return [], f"invalid candidate json: {exc}"
    payload_date = str(payload.get("date") or "")
    if payload_date != today.isoformat():
        return [], f"candidate file date {payload_date or 'missing'} != today {today.isoformat()}"

    signals: list[PremarketSignal] = []
    for raw in payload.get("candidates", []):
        symbol = normalize_symbol(raw.get("symbol"))
        decision = str(raw.get("decision", "candidate")).lower().strip()
        catalyst = str(raw.get("catalyst") or raw.get("thesis") or raw.get("reason") or "").strip()
        if not symbol or decision not in TRADE_DECISIONS or not catalyst:
            continue
        raw_sources = raw.get("sources") or raw.get("mcp_sources") or []
        if isinstance(raw_sources, str):
            sources = tuple(s.strip() for s in raw_sources.split(",") if s.strip())
        else:
            sources = tuple(str(s).strip() for s in raw_sources if str(s).strip())
        signals.append(PremarketSignal(
            symbol=symbol,
            catalyst=catalyst,
            mcp_score=_as_decimal(raw.get("mcp_score", raw.get("score", "0"))),
            sources=sources,
            exchange=str(raw.get("exchange") or "").upper().strip() or None,
            decision=decision,
            notes=str(raw.get("notes") or "").strip(),
        ))
    return signals, "ok" if signals else "no trade candidates in candidate file"


def filter_signals_by_liquidity(
    signals: Iterable[PremarketSignal],
    top_by_volume: Iterable[Candidate],
    *,
    limit: int | None = None,
) -> tuple[list[tuple[PremarketSignal, Candidate]], list[str]]:
    liquidity_by_symbol = {c.symbol: c for c in top_by_volume}
    selected: list[tuple[PremarketSignal, Candidate]] = []
    skipped: list[str] = []
    for signal in signals:
        liquid = liquidity_by_symbol.get(signal.symbol)
        if liquid is None:
            skipped.append(f"{signal.symbol}:not_in_top_volume_liquidity_filter")
            continue
        selected.append((signal, liquid))
    selected.sort(key=lambda pair: pair[0].mcp_score, reverse=True)
    if limit is not None and limit > 0:
        return selected[:limit], skipped
    return selected, skipped


def empty_candidate_payload(today: date | None = None) -> dict[str, object]:
    today = today or date.today()
    return {
        "date": today.isoformat(),
        "source": "TradingView MCP screening over top-100-volume liquidity filter",
        "liquidity_filter": "generated by python -m codex_trader.research_export",
        "candidates": [],
    }
